export const specialLogic = {
    'display': {
        'd-flex': 'flex',
        'hidden': 'none'
    },
    'position': true,
    'width': {
        'w-screen': '100vw',
    },
    'min-width': {
        'min-w-screen': '100vw',
    },
    'max-width': {
        'max-w-screen': '100vw',
        'max-w-none': 'none',
    },
    'height': {
        'h-screen': '100vh',
    },
    'min-height': {
        'min-h-screen': '100vh',
    },
    'max-height': {
        'max-h-screen': '100vh',
    },
    'font-weight': {
        'font-thin': '100',
        'font-extralight': '200',
        'font-light': '300',
        'font-normal': '400',
        'font-medium': '500',
        'font-semibold': '600',
        'font-bold': '700',
        'font-extrabold': '800',
        'font-black': '900',
    },
    'font-size': {
        'text-xxs': '10px',
        'text-xs': '12px',
        'text-sm': '14px',
        'text-base': '16px',
        'text-lg': '18px',
        'text-xl': '20px',
        'text-xl1': '21px',
        'text-xl2': '22px',
        'text-2xl': '24px',
        'text-2xl2': '26px',
        'text-2xl4': '28px',
        'text-3xl': '30px',
        'text-3xl2': '32px',
        'text-4xl': '36px',
        'text-5xl': '48px',
        'text-6xl': '60px',
        'text-7xl': '72px',
        'text-8xl': '96px',
        'text-9xl': '128px',
    },
    'line-height': {
        'leading-none': '1',
        'leading-tight': '1.25',
        'leading-snug': '1.375',
        'leading-normal': '1.5',
        'leading-relaxed': '1.625',
        'leading-loose': '2',
    },
    'white-space': {
        'whitespace-normal': 'normal',
        'whitespace-nowrap': 'nowrap',
        'whitespace-pre': 'pre',
        'whitespace-pre-line': 'pre-line',
        'whitespace-pre-wrap': 'pre-wrap',
        'whitespace-break-spaces': 'break-spaces',
    },
    'user-select': {
        'select-none': 'none',
        'select-text': 'text',
        'select-all': 'all',
        'select-auto': 'auto',
    },
    'flex-direction': {
        'flex-row': 'row',
        'flex-row-reverse': 'row-reverse',
        'flex-col': 'column',
        'flex-col-reverse': 'column-reverse',
    },
    'flex-grow': {
        'grow': '1',
        'grow-0': '0',
    },
    'flex-shrink': {
        'shrink': '1',
        'shrink-0': '0',
    },
    'justify-content': {
        'justify-normal': 'normal',
        'justify-start': 'flex-start',
        'justify-end': 'flex-end',
        'justify-center': 'center',
        'justify-between': 'space-between',
        'justify-around': 'around',
        'justify-evenly': 'space-evenly',
        'justify-stretch': 'stretch',
    },
    'align-items': {
        'items-start': 'flex-start',
        'items-end': 'flex-end',
        'items-center': 'flex-start',
        'items-baseline': 'baseline',
        'items-stretch': 'stretch',
    },
    'align-content': {
        'content-normal': 'normal',
        'content-center': 'center',
        'content-start': 'flex-start',
        'content-end': 'flex-end',
        'content-between': 'space-between',
        'content-around': 'space-around',
        'content-evenly': 'space-evenly',
        'content-baseline': 'baseline',
        'content-stretch': 'stretch',
    },
    'align-self': {
        'self-auto': 'auto',
        'self-start': 'flex-start',
        'self-end': 'flex-end',
        'self-center': 'center',
        'self-stretch': 'stretch',
        'self-baseline': 'baseline',
    },
    'flex-wrap': {
        'flex-wrap': 'wrap',
        'flex-wrap-reverse': 'wrap-reverse',
        'flex-nowrap': 'nowrap',
    },
    'order': {
        'order-first': '-9999',
        'order-last': '9999',
        'order-none': '0',
    }
}