const specialLogic = {
    'display': {
        'block': 'block',
        'inline-block': 'inline-block',
        'inline': 'inline',
        'd-flex': 'flex',
        'flex': 'flex',
        'inline-flex': 'inline-flex',
        'd-table': 'table',
        'table': 'table',
        'inline-table': 'inline-table',
        'table-caption': 'table-caption',
        'table-cell': 'table-cell',
        'table-column': 'table-column',
        'table-column-group': 'table-column-group',
        'table-footer-group': 'table-footer-group',
        'table-header-group': 'table-header-group',
        'table-row-group': 'table-row-group',
        'table-row-line': 'table-row',
        'flow-root': 'flow-root',
        'grid': 'grid',
        'inline-grid': 'inline-grid',
        'contents': 'contents',
        'list-item': 'list-item',
        'hidden': 'none'
    },
    'position': {
        'static': 'static',
        'absolute': 'absolute',
        'relative': 'relative',
        'sticky': 'sticky',
        'fixed': 'fixed',
    },
    'width': {
        'w-screen': '100vw',
    },
    'min-width': {
        'min-w-screen': '100vw',
    },
    'max-width': {
        'max-w-screen': '100vw',
        'max-w-none': 'none',
    },
    'height': {
        'h-screen': '100vh',
    },
    'min-height': {
        'min-h-screen': '100vh',
    },
    'max-height': {
        'max-h-screen': '100vh',
    },
    'font-weight': {
        'font-thin': '100',
        'font-extralight': '200',
        'font-light': '300',
        'font-normal': '400',
        'font-medium': '500',
        'font-semibold': '600',
        'font-bold': '700',
        'font-extrabold': '800',
        'font-black': '900',
    },
    'font-style': {
        'italic': 'italic',
        'non-italic': 'normal',
    },
    'font-size': {
        'text-xxs': '10px',
        'text-xs': '12px',
        'text-sm': '14px',
        'text-base': '16px',
        'text-lg': '18px',
        'text-xl': '20px',
        'text-xl1': '21px',
        'text-xl2': '22px',
        'text-2xl': '24px',
        'text-2xl2': '26px',
        'text-2xl4': '28px',
        'text-3xl': '30px',
        'text-3xl2': '32px',
        'text-4xl': '36px',
        'text-5xl': '48px',
        'text-6xl': '60px',
        'text-7xl': '72px',
        'text-8xl': '96px',
        'text-9xl': '128px',
    },
    'line-height': {
        'leading-none': '1',
        'leading-tight': '1.25',
        'leading-snug': '1.375',
        'leading-normal': '1.5',
        'leading-relaxed': '1.625',
        'leading-loose': '2',
    },
    'white-space': {
        'whitespace-normal': 'normal',
        'whitespace-nowrap': 'nowrap',
        'whitespace-pre': 'pre',
        'whitespace-pre-line': 'pre-line',
        'whitespace-pre-wrap': 'pre-wrap',
        'whitespace-break-spaces': 'break-spaces',
    },
    'user-select': {
        'select-none': 'none',
        'select-text': 'text',
        'select-all': 'all',
        'select-auto': 'auto',
    },
    'flex-direction': {
        'flex-row': 'row',
        'flex-row-reverse': 'row-reverse',
        'flex-col': 'column',
        'flex-col-reverse': 'column-reverse',
    },
    'justify-content': {
        'justify-normal': 'normal',
        'justify-start': 'flex-start',
        'justify-end': 'flex-end',
        'justify-center': 'center',
        'justify-between': 'space-between',
        'justify-around': 'around',
        'justify-evenly': 'space-evenly',
        'justify-stretch': 'stretch',
    },
    'align-items': {
        'items-start': 'flex-start',
        'items-end': 'flex-end',
        'items-center': 'center',
        'items-baseline': 'baseline',
        'items-stretch': 'stretch',
    },
    'align-content': {
        'content-normal': 'normal',
        'content-center': 'center',
        'content-start': 'flex-start',
        'content-end': 'flex-end',
        'content-between': 'space-between',
        'content-around': 'space-around',
        'content-evenly': 'space-evenly',
        'content-baseline': 'baseline',
        'content-stretch': 'stretch',
    },
    'align-self': {
        'self-auto': 'auto',
        'self-start': 'flex-start',
        'self-end': 'flex-end',
        'self-center': 'center',
        'self-stretch': 'stretch',
        'self-baseline': 'baseline',
    },
    'flex-wrap': {
        'flex-wrap': 'wrap',
        'flex-wrap-reverse': 'wrap-reverse',
        'flex-nowrap': 'nowrap',
    },
    'order': {
        'order-first': '-9999',
        'order-last': '9999',
        'order-none': '0',
    },
    'cursor': {
        'cursor-auto': 'auto',
        'cursor-default': 'default',
        'cursor-pointer': 'pointer',
        'cursor-wait': 'wait',
        'cursor-text': 'text',
        'cursor-move': 'move',
        'cursor-help': 'help',
        'cursor-not-allowed': 'not-allowed',
        'cursor-none': 'none',
        'cursor-context-menu': 'context-menu',
        'cursor-progress': 'progress',
        'cursor-cell': 'cell',
        'cursor-crosshair': 'crosshair',
        'cursor-vertical-text': 'vertical-text',
        'cursor-alias': 'alias',
        'cursor-copy': 'copy',
        'cursor-no-drop': 'no-drop',
        'cursor-grab': 'grab',
        'cursor-grabbing': 'grabbing',
        'cursor-all-scroll': 'all-scroll',
        'cursor-col-resize': 'col-resize',
        'cursor-row-resize': 'row-resize',
        'cursor-n-resize': 'n-resize',
        'cursor-e-resize': 'e-resize',
        'cursor-s-resize': 's-resize',
        'cursor-w-resize': 'w-resize',
        'cursor-ne-resize': 'ne-resize',
        'cursor-nw-resize': 'nw-resize',
        'cursor-se-resize': 'se-resize',
        'cursor-sw-resize': 'sw-resize',
        'cursor-ew-resize': 'ew-resize',
        'cursor-ns-resize': 'ns-resize',
        'cursor-nesw-resize': 'nesw-resize',
        'cursor-nwse-resize': 'nwse-resize',
        'cursor-zoom-in': 'zoom-in',
        'cursor-zoom-out': 'zoom-out',
    },
    'text-align': {
        'text-left': 'left',
        'text-center': 'center',
        'text-right': 'right',
        'text-justify': 'justify',
        'text-start': 'start',
        'text-end': 'end',
    },
    'letter-spacing': {
        'tracking-tighter': '-0.05em',
        'tracking-tight': '-0.025em',
        'tracking-normal': '0em',
        'tracking-wide': '0.025em',
        'tracking-wider': '0.05em',
        'tracking-widest': '0.1em',
    },
    'text-transform': {
        'uppercase': 'uppercase',
        'lowercase': 'lowercase',
        'capitalize': 'capitalize',
        'normal-case': 'none',
    },
    'text-decoration': {
        'underline': 'underline',
        'overline': 'overline',
        'line-through': 'line-through',
        'no-underline': 'none',
    },
    'overflow': {
        'overflow-auto': 'auto',
        'overflow-hidden': 'hidden',
        'overflow-clip': 'clip',
        'overflow-visible': 'visible',
        'overflow-scroll': 'scroll',
    },
    'overflow-x': {
        'overflow-x-auto': 'auto',
        'overflow-x-hidden': 'hidden',
        'overflow-x-clip': 'clip',
        'overflow-x-visible': 'visible',
        'overflow-x-scroll': 'scroll',
    },
    'overflow-y': {
        'overflow-y-auto': 'auto',
        'overflow-y-hidden': 'hidden',
        'overflow-y-clip': 'clip',
        'overflow-y-visible': 'visible',
        'overflow-y-scroll': 'scroll',
    },
    'object-fit': {
        'object-contain': 'contain',
        'object-cover': 'cover',
        'object-fill': 'fill',
        'object-none': 'none',
        'object-scale-down': 'scale-down',
    },
    'border-style': {
        'border-solid': 'solid',
        'border-dashed': 'dashed',
        'border-dotted': 'dotted',
        'border-double': 'double',
        'border-hidden': 'hidden',
        'border-none': 'none',
    },
    'background-size': {
        'bg-auto': 'auto',
        'bg-cover': 'cover',
        'bg-contain': 'contain',
    },
    'background-repeat': {
        'bg-repeat': 'repeat',
        'bg-no-repeat': 'no-repeat',
        'bg-repeat-x': 'repeat-x',
        'bg-repeat-y': 'repeat-y',
        'bg-repeat-round': 'round',
        'bg-repeat-space': 'space',
    },
    'text-overflow': {
        'text-ellipsis': 'ellipsis',
        'text-clip': 'clip',
    },
    'justify-items': {
        'justify-items-start': 'start',
        'justify-items-end': 'end',
        'justify-items-center': 'center',
        'justify-items-stretch': 'stretch',
    },
    'place-items': {
      'place-items-start': 'start',
      'place-items-end': 'end',
      'place-items-center': 'center',
      'place-items-baseline': 'baseline',
      'place-items-stretch': 'stretch',
    },
    'border-collapse': {
        'border-collapse': 'collapse',
        'border-separate': 'separate',
    },
    'table-layout': {
        'table-auto': 'auto',
        'table-fixed': 'fixed',
    },
}

module.exports = {
  specialLogic,
};
