const rulesForStaticClasses = {
    'flex-direction': {
        'flex-row': 'row',
        'flex-row-reverse': 'row-reverse',
        'flex-col': 'column',
        'flex-col-reverse': 'column-reverse',
    },
    'flex-wrap': {
        'flex-wrap': 'wrap',
        'flex-wrap-reverse': 'wrap-reverse',
        'flex-nowrap': 'nowrap',
    },
    'justify-items': {
        'justify-items-start': 'start',
        'justify-items-end': 'end',
        'justify-items-center': 'center',
        'justify-items-stretch': 'stretch',
    },
    'justify-content': {
        'justify-normal': 'normal',
        'justify-start': 'flex-start',
        'justify-end': 'flex-end',
        'justify-center': 'center',
        'justify-between': 'space-between',
        'justify-around': 'space-around',
        'justify-evenly': 'space-evenly',
        'justify-stretch': 'stretch',
    },
    'justify-self': {
        'justify-self-auto': 'auto',
        'justify-self-start': 'start',
        'justify-self-end': 'end',
        'justify-self-center': 'center',
        'justify-self-stretch': 'stretch',
    },
    'align-content': {
        'content-normal': 'normal',
        'content-center': 'center',
        'content-start': 'flex-start',
        'content-end': 'flex-end',
        'content-between': 'space-between',
        'content-around': 'space-around',
        'content-evenly': 'space-evenly',
        'content-baseline': 'baseline',
        'content-stretch': 'stretch',
    },
    'align-items': {
        'items-start': 'flex-start',
        'items-end': 'flex-end',
        'items-center': 'center',
        'items-baseline': 'baseline',
        'items-stretch': 'stretch',
    },
    'align-self': {
        'self-auto': 'auto',
        'self-start': 'flex-start',
        'self-end': 'flex-end',
        'self-center': 'center',
        'self-stretch': 'stretch',
        'self-baseline': 'baseline',
    },
    'place-content': {
        'place-content-center': 'center',
        'place-content-start': 'start',
        'place-content-end': 'end',
        'place-content-between': 'space-between',
        'place-content-around': 'space-around',
        'place-content-evenly': 'space-evenly',
        'place-content-baseline': 'baseline',
        'place-content-stretch': 'stretch',
    },
    'place-items': {
        'place-items-start': 'start',
        'place-items-end': 'end',
        'place-items-center': 'center',
        'place-items-baseline': 'baseline',
        'place-items-stretch': 'stretch',
    },
    'place-self': {
        'place-self-auto': 'auto',
        'place-self-start': 'start',
        'place-self-end': 'end',
        'place-self-center': 'center',
        'place-self-stretch': 'stretch',
    },
    'display': {
        'block': 'block',
        'inline-block': 'inline-block',
        'inline': 'inline',
        'd-flex': 'flex',
        'flex': 'flex',
        'inline-flex': 'inline-flex',
        'd-table': 'table',
        'table': 'table',
        'inline-table': 'inline-table',
        'table-caption': 'table-caption',
        'table-cell': 'table-cell',
        'table-column': 'table-column',
        'table-column-group': 'table-column-group',
        'table-footer-group': 'table-footer-group',
        'table-header-group': 'table-header-group',
        'table-row-group': 'table-row-group',
        'table-row-line': 'table-row',
        'flow-root': 'flow-root',
        'grid': 'grid',
        'inline-grid': 'inline-grid',
        'contents': 'contents',
        'list-item': 'list-item',
        'hidden': 'none'
    },
    'position': {
        'static': 'static',
        'absolute': 'absolute',
        'relative': 'relative',
        'sticky': 'sticky',
        'fixed': 'fixed',
    },
    'overflow': {
        'overflow-auto': 'auto',
        'overflow-hidden': 'hidden',
        'overflow-clip': 'clip',
        'overflow-visible': 'visible',
        'overflow-scroll': 'scroll',
    },
    'overflow-x': {
        'overflow-x-auto': 'auto',
        'overflow-x-hidden': 'hidden',
        'overflow-x-clip': 'clip',
        'overflow-x-visible': 'visible',
        'overflow-x-scroll': 'scroll',
    },
    'overflow-y': {
        'overflow-y-auto': 'auto',
        'overflow-y-hidden': 'hidden',
        'overflow-y-clip': 'clip',
        'overflow-y-visible': 'visible',
        'overflow-y-scroll': 'scroll',
    },
    'object-fit': {
        'object-contain': 'contain',
        'object-cover': 'cover',
        'object-fill': 'fill',
        'object-none': 'none',
        'object-scale-down': 'scale-down',
    },
    'object-position': {
        'object-bottom': 'bottom',
        'object-center': 'center',
        'object-left': 'left',
        'object-left-bottom': 'left bottom',
        'object-left-top': 'left top',
        'object-right': 'right',
        'object-right-bottom': 'right bottom',
        'object-right-top': 'right top',
        'object-top': 'top',
    },
    'visibility': {
        'visible': 'visible',
        'invisible': 'hidden',
        'collapse': 'collapse',
    },
    'grid-column': {
        'col-auto': 'auto',
        'col-span-full': '1 / -1',
    },
    'border-collapse': {
        'border-collapse': 'collapse',
        'border-separate': 'separate',
    },
    'table-layout': {
        'table-auto': 'auto',
        'table-fixed': 'fixed',
    },
    'font-size': {
        'text-xxs': '10px',
        'text-xs': '12px',
        'text-sm': '14px',
        'text-base': '16px',
        'text-lg': '18px',
        'text-xl': '20px',
        'text-xl1': '21px',
        'text-xl2': '22px',
        'text-2xl': '24px',
        'text-2xl2': '26px',
        'text-2xl4': '28px',
        'text-3xl': '30px',
        'text-3xl2': '32px',
        'text-4xl': '36px',
        'text-5xl': '48px',
        'text-6xl': '60px',
        'text-7xl': '72px',
        'text-8xl': '96px',
        'text-9xl': '128px',
    },
    'font-style': {
        'italic': 'italic',
        'not-italic': 'normal',
    },
    'font-weight': {
        'font-thin': '100',
        'font-extralight': '200',
        'font-light': '300',
        'font-normal': '400',
        'font-medium': '500',
        'font-semibold': '600',
        'font-bold': '700',
        'font-extrabold': '800',
        'font-black': '900',
    },
    'text-align': {
        'text-left': 'left',
        'text-center': 'center',
        'text-right': 'right',
        'text-justify': 'justify',
        'text-start': 'start',
        'text-end': 'end',
    },
    'text-overflow': {
        'text-ellipsis': 'ellipsis',
        'text-clip': 'clip',
    },
    'background-size': {
        'bg-auto': 'auto',
        'bg-cover': 'cover',
        'bg-contain': 'contain',
    },
    'background-repeat': {
        'bg-repeat': 'repeat',
        'bg-no-repeat': 'no-repeat',
        'bg-repeat-x': 'repeat-x',
        'bg-repeat-y': 'repeat-y',
        'bg-repeat-round': 'round',
        'bg-repeat-space': 'space',
    },
    'border-style': {
        'border-solid': 'solid',
        'border-dashed': 'dashed',
        'border-dotted': 'dotted',
        'border-double': 'double',
        'border-hidden': 'hidden',
        'border-none': 'none',
    },
    'text-decoration': {
        'underline': 'underline',
        'overline': 'overline',
        'line-through': 'line-through',
        'no-underline': 'none',
    },
    'text-transform': {
        'uppercase': 'uppercase',
        'lowercase': 'lowercase',
        'capitalize': 'capitalize',
        'normal-case': 'none',
    },
    'white-space': {
        'whitespace-normal': 'normal',
        'whitespace-nowrap': 'nowrap',
        'whitespace-pre': 'pre',
        'whitespace-pre-line': 'pre-line',
        'whitespace-pre-wrap': 'pre-wrap',
        'whitespace-break-spaces': 'break-spaces',
    },
    'user-select': {
        'select-none': 'none',
        'select-text': 'text',
        'select-all': 'all',
        'select-auto': 'auto',
    },
    'cursor': {
        'cursor-auto': 'auto',
        'cursor-default': 'default',
        'cursor-pointer': 'pointer',
        'cursor-wait': 'wait',
        'cursor-text': 'text',
        'cursor-move': 'move',
        'cursor-help': 'help',
        'cursor-not-allowed': 'not-allowed',
        'cursor-none': 'none',
        'cursor-context-menu': 'context-menu',
        'cursor-progress': 'progress',
        'cursor-cell': 'cell',
        'cursor-crosshair': 'crosshair',
        'cursor-vertical-text': 'vertical-text',
        'cursor-alias': 'alias',
        'cursor-copy': 'copy',
        'cursor-no-drop': 'no-drop',
        'cursor-grab': 'grab',
        'cursor-grabbing': 'grabbing',
        'cursor-all-scroll': 'all-scroll',
        'cursor-col-resize': 'col-resize',
        'cursor-row-resize': 'row-resize',
        'cursor-n-resize': 'n-resize',
        'cursor-e-resize': 'e-resize',
        'cursor-s-resize': 's-resize',
        'cursor-w-resize': 'w-resize',
        'cursor-ne-resize': 'ne-resize',
        'cursor-nw-resize': 'nw-resize',
        'cursor-se-resize': 'se-resize',
        'cursor-sw-resize': 'sw-resize',
        'cursor-ew-resize': 'ew-resize',
        'cursor-ns-resize': 'ns-resize',
        'cursor-nesw-resize': 'nesw-resize',
        'cursor-nwse-resize': 'nwse-resize',
        'cursor-zoom-in': 'zoom-in',
        'cursor-zoom-out': 'zoom-out',
    },
    'word-break': {
        'break-normal': 'normal',
        'break-all': 'break-all',
        'break-keep': 'keep-all',
    },
    'vertical-align': {
        'align-baseline': 'baseline',
        'align-top': 'top',
        'align-middle': 'middle',
        'align-bottom': 'bottom',
        'align-text-top': 'text-top',
        'align-text-bottom': 'text-bottom',
        'align-sub': 'sub',
        'align-super': 'super',
    },
    'flex-shrink': {
        'shrink-0': '0',
        'shrink': '1',
    }
}

module.exports = {
    rulesForStaticClasses,
};